// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWD1813.Models;

#nullable disable

namespace SWD1813.Migrations
{
    [DbContext(typeof(ProjectManagementContext))]
    [Migration("20260324021853_FixUnicodeNamesNvarchar")]
    partial class FixUnicodeNamesNvarchar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWD1813.Models.ApiIntegration", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("integration_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GithubToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("github_token");

                    b.Property<string>("JiraToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jira_token");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.HasKey("IntegrationId")
                        .HasName("PK__api_inte__B403D887F56342C5");

                    b.HasIndex("ProjectId");

                    b.ToTable("api_integrations", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.ChatMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("message_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("content");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId")
                        .HasName("PK__chat_messages");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_chat_messages_project_id");

                    b.HasIndex(new[] { "SentAt" }, "IX_chat_messages_sent_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Commit", b =>
                {
                    b.Property<string>("CommitId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("commit_id");

                    b.Property<int?>("Additions")
                        .HasColumnType("int")
                        .HasColumnName("additions");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("author_email");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("author_name");

                    b.Property<DateTime?>("CommitDate")
                        .HasColumnType("datetime")
                        .HasColumnName("commit_date");

                    b.Property<int?>("Deletions")
                        .HasColumnType("int")
                        .HasColumnName("deletions");

                    b.Property<int?>("FilesChanged")
                        .HasColumnType("int")
                        .HasColumnName("files_changed");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("RepoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("repo_id");

                    b.HasKey("CommitId")
                        .HasName("PK__commits__1C807873FB86E5C7");

                    b.HasIndex("RepoId");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.ContributorStat", b =>
                {
                    b.Property<string>("StatId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("stat_id");

                    b.Property<DateTime?>("LastCommit")
                        .HasColumnType("datetime")
                        .HasColumnName("last_commit");

                    b.Property<string>("RepoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("repo_id");

                    b.Property<int?>("TotalAdditions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_additions");

                    b.Property<int?>("TotalCommits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_commits");

                    b.Property<int?>("TotalDeletions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_deletions");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("StatId")
                        .HasName("PK__contribu__B8A52560876E2F63");

                    b.HasIndex("RepoId");

                    b.HasIndex("UserId");

                    b.ToTable("contributor_stats", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("group_name");

                    b.Property<string>("LecturerId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("lecturer_id");

                    b.HasKey("GroupId")
                        .HasName("PK__groups__D57795A0A10388A7");

                    b.HasIndex("LecturerId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.GroupMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("GroupId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__group_me__3213E83FE9BCBDC5");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.JiraIssue", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_id");

                    b.Property<string>("Assignee")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("assignee");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("IssueKey")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_key");

                    b.Property<string>("IssueType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_type");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("IssueId")
                        .HasName("PK__jira_iss__D6185C3980FAD455");

                    b.HasIndex("ProjectId");

                    b.ToTable("jira_issues", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("lecturer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("LecturerId")
                        .HasName("PK__lecturer__D4D1DAB15638DEF7");

                    b.HasIndex(new[] { "UserId" }, "UQ__lecturer__B9BE370EB3C91E72")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("lecturers", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GroupId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("group_id");

                    b.Property<string>("JiraProjectKey")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("jira_project_key");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("ProjectId")
                        .HasName("PK__projects__BC799E1FC8A80DF7");

                    b.HasIndex("GroupId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("report_id");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_url");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("generated_by");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("report_type");

                    b.HasKey("ReportId")
                        .HasName("PK__reports__779B7C589DA9364A");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("ProjectId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Repository", b =>
                {
                    b.Property<string>("RepoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("repo_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GithubOwner")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("github_owner");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("RepoName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("repo_name");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("repo_url");

                    b.HasKey("RepoId")
                        .HasName("PK__reposito__E2D3BC802CCE93E8");

                    b.HasIndex("ProjectId");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Sprint", b =>
                {
                    b.Property<string>("SprintId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("sprint_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("project_id");

                    b.Property<string>("SprintName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sprint_name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SprintId")
                        .HasName("PK__sprints__396C18028DF547C0");

                    b.HasIndex("ProjectId");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.Task", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("task_id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("assigned_to");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("IssueId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_id");

                    b.Property<int?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("TaskId")
                        .HasName("PK__tasks__0492148D0EA24106");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("IssueId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F99F0A1FB");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E616418C614EB")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SWD1813.Models.ApiIntegration", b =>
                {
                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("ApiIntegrations")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__api_integ__proje__06CD04F7");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SWD1813.Models.ChatMessage", b =>
                {
                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_chat_messages_projects");

                    b.HasOne("SWD1813.Models.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_chat_messages_users");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD1813.Models.Commit", b =>
                {
                    b.HasOne("SWD1813.Models.Repository", "Repo")
                        .WithMany("Commits")
                        .HasForeignKey("RepoId")
                        .HasConstraintName("FK__commits__repo_id__778AC167");

                    b.Navigation("Repo");
                });

            modelBuilder.Entity("SWD1813.Models.ContributorStat", b =>
                {
                    b.HasOne("SWD1813.Models.Repository", "Repo")
                        .WithMany("ContributorStats")
                        .HasForeignKey("RepoId")
                        .HasConstraintName("FK__contribut__repo___7E37BEF6");

                    b.HasOne("SWD1813.Models.User", "User")
                        .WithMany("ContributorStats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__contribut__user___7D439ABD");

                    b.Navigation("Repo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD1813.Models.Group", b =>
                {
                    b.HasOne("SWD1813.Models.Lecturer", "Lecturer")
                        .WithMany("Groups")
                        .HasForeignKey("LecturerId")
                        .HasConstraintName("FK__groups__lecturer__5DCAEF64");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("SWD1813.Models.GroupMember", b =>
                {
                    b.HasOne("SWD1813.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__group_mem__group__619B8048");

                    b.HasOne("SWD1813.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__group_mem__user___628FA481");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD1813.Models.JiraIssue", b =>
                {
                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("JiraIssues")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__jira_issu__proje__6D0D32F4");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SWD1813.Models.Lecturer", b =>
                {
                    b.HasOne("SWD1813.Models.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("SWD1813.Models.Lecturer", "UserId")
                        .HasConstraintName("FK__lecturers__user___59FA5E80");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD1813.Models.Project", b =>
                {
                    b.HasOne("SWD1813.Models.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__projects__group___66603565");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SWD1813.Models.Report", b =>
                {
                    b.HasOne("SWD1813.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .HasConstraintName("FK__reports__generat__02FC7413");

                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__reports__project__02084FDA");

                    b.Navigation("GeneratedByNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SWD1813.Models.Repository", b =>
                {
                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__repositor__proje__6A30C649");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SWD1813.Models.Sprint", b =>
                {
                    b.HasOne("SWD1813.Models.Project", "Project")
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__sprints__project__74AE54BC");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SWD1813.Models.Task", b =>
                {
                    b.HasOne("SWD1813.Models.User", "AssignedToNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK__tasks__assigned___71D1E811");

                    b.HasOne("SWD1813.Models.JiraIssue", "Issue")
                        .WithMany("Tasks")
                        .HasForeignKey("IssueId")
                        .HasConstraintName("FK__tasks__issue_id__70DDC3D8");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("SWD1813.Models.Group", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SWD1813.Models.JiraIssue", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SWD1813.Models.Lecturer", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SWD1813.Models.Project", b =>
                {
                    b.Navigation("ApiIntegrations");

                    b.Navigation("ChatMessages");

                    b.Navigation("JiraIssues");

                    b.Navigation("Reports");

                    b.Navigation("Repositories");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("SWD1813.Models.Repository", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("ContributorStats");
                });

            modelBuilder.Entity("SWD1813.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ContributorStats");

                    b.Navigation("GroupMembers");

                    b.Navigation("Lecturer");

                    b.Navigation("Reports");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
